/**
 * Created by xujie on 2018/2/5.
 */


module.exports = {
    secretkeyErr:{
      code:"-2",
      msg:"secretKey错误"
    },
    tokenLess:{
        code:"-1",
        msg:"token缺失"
    },
    tokeInvalid:{
      code:"-2",
       msg:"token失效"
    },
    notAdmin:{
        code:-3,
        msg:"不是管理员"
    },
    notJurisdiction:{
        code:-4,
        msg:"您没有权限"
    },
    paramsLess:{
        code:10000,
        msg:"参数缺失"
    },

    sqlErr:{
        code:10001,
        msg:"操作数据库错误"
    },
    usernameLess:{
        code:10002,
        msg:"用户名缺失"
    },
    passwordLess:{
        code:10003,
        msg:"密码缺失"
    },
    hasRegister:{
        code:10004,
        msg:"号码已被注册"
    },
    noRegister:{
        code:10005,
        msg:"该用户尚未注册"
    },
    passwordErr:{
        code:10006,
        msg:"密码错误"
    },
    classfyIdLess:{
        code:20000,
        msg:"文章分类classfyId为空"
    },
    noArticle:{
        code:20001,
        msg:"文章不存在"
    },
    articleIdLess:{
        code:20002,
        msg:"文章id缺失"
    },
    noClassfy:{
        code:20003,
        msg:"没有此类别"
    },
    mdLess:{
        code:20003,
        msg:"文章内容为null"
    },
    appNameLess:{
        code:30000,
        msg:"专题名称的name缺失"
    },
    appIdLess:{
        code:30001,
        msg:"专题的id缺失"
    },
    appTitleLess:{
        code:30002,
        msg:"专题的标题缺失"
    },
    noApp:{
        code:30003,
        msg:"没有找到该专题"
    },
    emailSendFaiure:{
        code:4000,
        msg:"邮件发送失败"
    },
    emailIsNull:{
        code:40001,
        msg:"邮箱不能为空"
    },
    phoneEmpty:{
        code:50001,
         msg:"手机号码为空"
    },
    phoneFormatErr:{
        code:50002,
        msg:"手机号码格式错误"
    },
    timeLessOneMinutes:{
        code:50003,
        msg:"距离上次间隔小于90s"
    },

    verifyCodeLess:{
        code:50004,
        msg:"验证码丢失"
    },
    verifyCodeInvalid:{
        code:50005,
        msg:"验证码失效"
    },
    timeLessHalfHour:{
        code:50006,
        msg:"请半个小时后尝试"
    },
    fileUploadErr:{
        code:60000,
        msg:"文件上传失败"
    },
    noComment:{
        code:70000,
        msg:"该评论已删除"
    },
    hasFollow:{
        code:80000,
        msg:"您已经关注"
    },
    notFollow:{
        code:80001,
        msg:"您未关注此用户"
    },
    questionTitleLess:{
        code:9000,
        msg:"标题缺失"
    },
    questionContentLess:{
        code:90001,
        msg:"描述不能为空"
    },
    noQuestion:{
        code:90002,
        msg:"没有找到问题"
    },

    noAnswer:{
        code:90003,
        msg:"没有找到答案"
    },

    noProgramType:{
        code:100001,
        msg:"没有找到程序类型"
    }


}